host: host.example.com
port: 1521
username: username
password: password
dbname: orcl
import_sql: false
template_name: default.go.tpl
package_name: models
model_path: models

upper_case_json: false
ignore_unsupport_type: false
